[ids]
*

[main]
# 右 Alt 键映射为右 Ctrl 键
rightalt = rightcontrol

# work: hold + key => shortcuts 
capslock = overload(meta, esc)
#  work: hold + uiop ==> arrow
leftalt = layer(nav)

[nav]
h = left
j = down
k = up
l = right
